kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
  - name: test
    image: golang
    commands:
      - go list | grep -v sudo_test | xargs go test -v .
      - su -c 'go test -v ./sudo_test'

  - name: lint
    image: golang:1.16
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
      - golangci-lint run
